<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>Async Await</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
	<link rel="stylesheet" href="../base.css" />
</head>
<body style="display: flex; justify-content: center;">
	<div id="button" style="background-color: darkorange; color: white; font-weight: 600;" class="p-2 btn">Click !</div>
		
	<script>
		console.log("Async Await");

		// EXERCICE 1
		const wait = (time = 0) => new Promise(resolve => setTimeout(resolve, time))

		// 1.mark the function as async
		const test = async () => {
			console.log("start");
			// 2. add the await keyword allow to wait the Promise to be resolved
			await wait(1000)
			console.log("preparing ...");
			await wait(3000)
			console.log("finished");
		}
		test()

		// DIFFERENTES ECRITURES
		// declaration
		async function aaa () {}

		// arrow function 
		const bbb = async () => {}

		// callback
		const object = {
			ccc: async function () {}, 
			async ddd() {},
			eee: async () => {}
		}


		// EXERCICE 2
		function makePizza (topping) {
			// Promises are made imediatly but do not resolve until they are ready !!!
			return new Promise((resolve, reject) => {
				const timeToCook = 5 * (topping.length * 100)
				setTimeout(()=> {
				// resolving when it's done
				resolve(`your 🍕 is ${topping.join(" ")}`)
				}, timeToCook)
				// reject if something wrong
				if (topping.includes("pineapple")){
					reject(new Error("PineApple present : Must NOT be include"))
				}
			});
		}

		const createPizza = async () => {
			const pizzaPromise1 = await makePizza(["onion", "marshmalow"]);
			console.log(pizzaPromise1);
			const pizzaPromise2 =  await makePizza(["plant"]);
			console.log(pizzaPromise2);
		}
		createPizza()

		// display the both function at the same time
		const createPizza2 = async () => {
			const pizzaPromise1 = makePizza(["onion"]);
			const pizzaPromise2 = makePizza(["marshmalow"]);
			const [ onion, marchmalow ] = await Promise.all([pizzaPromise1, pizzaPromise2]);
			console.log(onion, marchmalow);
		}
		createPizza2()

		// EXERCICE 3 Refacto
		const btn = document.querySelector("#button");
			const animation = async (event) => {
				// 1. Change the text to GO immediatly
		 	 	event.currentTarget.innerText = "GO"

				// 2. Make it a circle after 2s
				await	wait(200)
				btn.style.borderRadius = "50%";

				// 3. Make it red after 0.5s
				await wait(500)
				btn.style.backgroundColor = "red";
				btn.style.color = "white";

				// 4. Make it square after 0.25s
				await wait(250)
				btn.style.borderRadius = "0%";
				
				// 5. Make it purple after 0.3s
				await wait(300)
				btn.style.backgroundColor = "#5f81ff";
				btn.style.color = "white";

				// 6. Fade out after 0.5s
				await wait(500)	
				btn.style.opacity = 0;
			}
			btn.addEventListener("click",animation ); 


		// EXERCIE 4 : HANDLING ERROR 1 (try/catch)
		// const go = async () => {
		// 	try { 
		// 		const pizza = await makePizza(["pineapple"])
		// 		console.log(pizza);
		// 	} catch (error) {
		// 		console.error(new Error(error))
		// 	}
		// };
		// go()

		// EXERCIE 5 : HANDLING ERROR 2 (catch it at run time)
		const handleError = (error) => {
			console.error(new Error(error))
		};

		// const go2 = async () => {
		// 	const pizza = await makePizza(['pineapple']).catch(handleError);
		// 	console.log(pizza);
		// };
		// const result2 = go2();
		// console.log(result2);
		
		// // _____________
		// const go3 = async () => {
		// 	const pizza = await makePizza(['pineapple'])
		// 	console.log(pizza);
		// };

		// go3()
		// .then(result => {
		// 	console.log(result)
		// })
		// .catch(handleError);

		// // EXERCIE 5 : As a safe function with HOF 
		// 		// HOF : Higher Order Function (function returning a function)
		const makeSafe = (fn, theErrorHandle) => {
			return function () {
				fn()
				.then(resp => console.log(resp))
				.catch(theErrorHandle)
			}
		}		

		const go4 = async () => {
			const pizza = await makePizza(['pineapple']);
			console.log(pizza);
		};

		const safeGo = makeSafe(go4, handleError);
		// this is easiest when we have a lot of function to check ! 
		safeGo();
	</script>
</body>
</html>